import type { Metadata } from "next";
import { LandingNav } from "@/components/landing/LandingNav";
import { LandingFooter } from "@/components/landing/LandingFooter";
import { LegalSection } from "@/components/common/LegalSection";

export const metadata: Metadata = {
  title: "Terms of Service | AvgDown",
  description: "Read the Terms of Service for AvgDown, an educational price monitoring and SMA alert notification tool.",
};

export default function TermsPage() {
  return (
    <div className="flex flex-col flex-1 w-full min-h-screen bg-background text-foreground antialiased">
      <LandingNav />

      <main className="flex-1 max-w-4xl mx-auto px-6 pt-32 pb-16">
        <h1 className="text-3xl font-extrabold tracking-tight sm:text-4xl mb-4 bg-gradient-to-r from-white to-white/60 bg-clip-text text-transparent">
          Terms of Service
        </h1>
        <p className="text-sm text-muted-foreground mb-8">Last updated: May 23, 2026</p>

        <div className="space-y-8 prose prose-invert max-w-none text-muted-foreground leading-relaxed text-sm">
          <LegalSection title="1. Nature of the Service (&quot;We are the Messenger&quot;)">
            <p className="mb-3">
              AvgDown is an automated data tracking and alert notification platform. By using this service, you
              acknowledge and agree that:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong>Automated Tool:</strong> We do not make, evaluate, or suggest investment decisions. The service
                simply queries public endpoints and triggers emails/webhooks based on parameters (symbols, averages,
                thresholds) that <strong>you</strong> configure.
              </li>
              <li>
                <strong>No Verification:</strong> We do not verify whether your alert criteria are financially sound,
                logical, or accurate. We are strictly the automated messenger carrying out your instructions.
              </li>
            </ul>
          </LegalSection>

          <LegalSection title="2. User Responsibility (Educational & Personal Study)">
            <p className="mb-3">
              This application is provided for general informational, educational, and personal study purposes (such as
              school projects, financial research, or academic studying).
            </p>
            <p>
              It is entirely up to you, the user, to decide how to apply the information or alerts generated by AvgDown.
              Whether you choose to use the tool for simulated portfolios, class assignments, or actual investing, you
              assume full responsibility for your actions.
            </p>
          </LegalSection>

          <LegalSection title="3. Disclaimer of Financial Advice">
            <p className="mb-3">
              AvgDown is <strong>not</strong> a registered broker-dealer, financial planner, or investment advisor.
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                No content, alerts, notifications, or calculations on this platform constitute investment, legal, tax,
                or financial advice.
              </li>
              <li>
                Past historical stock performance and Simple Moving Average calculations are not indicative of future
                market results.{" "}
              </li>
              <li>
                All pricing data is sourced via public APIs (e.g., Yahoo Finance) and may contain delays, discrepancies,
                or formatting errors. You should verify all data independently before making any real-world financial
                commitments.
              </li>
            </ul>
          </LegalSection>

          <LegalSection title="4. Limitation of Liability">
            <p>
              To the maximum extent permitted by law, AvgDown and its creators will not be liable for any direct,
              indirect, incidental, or consequential losses - including but not limited to trading losses, financial
              damage, missed market opportunities, server downtime, delayed alert deliveries, or data loss. You use this
              application entirely at your own risk.
            </p>
          </LegalSection>
        </div>
      </main>

      <LandingFooter />
    </div>
  );
}
